steps:
# - name: 'gcr.io/cloud-builders/gsutil'
#   args: ['-m', 'rsync', '-r', 'build/', 'gs://flaskbuckett']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t','asia-south1-docker.pkg.dev/block-convey-p1/flask-repo/flask-app:${SHORT_SHA}', '.' ]

- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'asia-south1-docker.pkg.dev/block-convey-p1/flask-repo/flask-app:${SHORT_SHA}']

# artifacts:
#   objects:
#     location: "us-central1"
#     paths:
#       - "Dockerfile"
#       - "app.py"
#       - "requirements.txt"
#   bucket: "gs://flaskbuckett"

  
substitutions:
  _BUCKET_NAME: flaskbuckett

images:
  - gcr.io/block-convey-p1/flask-repo/flask-app:${SHORT_SHA}




# - name: 'gcr.io/cloud-builders/python'
#   args: ['python', '-m', 'venv', 'env']
#   dir: 'my_flask_app'


# uild the Docker image
# - name: 'gcr.io/cloud-builders/python:3.8'
#   args: ['source', 'env/bin/activate']
#   dir: 'my_flask_app' 

# - name: 'gcr.io/cloud-builders/python:3.8'
#   args: ['pip', 'install', '-r', 'requirements.txt']
#   dir: 'my_flask_app' 

# - name: 'gcr.io/cloud-builders/python:3.8'
#   args: ['python', 'app.py']  
#   dir: 'my_flask_app'  

  # Install dependencies
# - name: python
#   entrypoint: pip
#   args: ["install", "-r", "/Users/jiteshaggarwal/Desktop/appOfFlask/my_flask_app/requirements.txt", "--user"]

# # Step 2: Build the Docker image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/your-project-id/flask-repo/my-backend:${SHORT_SHA}', '.' ]
#   dir: 'my_flask_app'  
 

# # Step 3: Push the Docker image to Google Artifact Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/block-convey-p1/flask-repo/my-backend:${SHORT_SHA}']

# images:
# - 'gcr.io/block-convey-p1/your-image-name:$COMMIT_SHA'
